root: true
env:
  node: true
  es2017: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2019
  sourceType: 'module'
plugins:
  - '@typescript-eslint'
rules:
  no-unused-vars: 'off'
  "@typescript-eslint/no-unused-vars": ['warn']
  semi: ['warn', 'always']
  no-param-reassign: ['error', { "props": true }]
